### ISSUE TITLE
about the Semantic querying cache

### ISSUE THREAD

**Issue by zhl-HFUT** [mayug/BaseTransformers#2]
I have been exploring the repository but unable to locate any relevant code related to this feature(generate Semantic querying cache), might I have overlooked it?

Additionally, the cache download links provided for CUB seem to be empty.

**Comment by mayug** [comment]
Hi,

Sorry about the delay. I have uploaded the cub cache and encoder weights for conv-4 as well as the semantic querying cache for cub dataset.

Regards
Mayug
